### ISSUE TITLE
Memory leak or not?

### ISSUE THREAD

**Issue by Const-me** [gavv/snippets#2]
Does this block of code

https://github.com/gavv/snippets/blob/master/udev/udev_list_usb_storage.c#L43-L70

leaks the resources pointed by `usb` variable? And if no, why?

**Comment by Const-me** [comment]
Appears to be OK. At least in recent versions of libuv.

Here’s the comment: https://cgit.freedesktop.org/systemd/systemd/tree/src/libudev/libudev-device.c#n471

> Returned device is not referenced. It is attached to the child device, and will be cleaned up when the child device is cleaned up.

**Comment by gavv** [comment]
Yeah, it should be okay.
